button sounds
fishfolks/punchy pull request #236
Opened 2022-08-21 21:50 UTC by DRuppFv

Note: I removed a lot of code that was not done

Just need help with playing the audio, the audio files are in the PR

2022-09-01 00:02 UTC, DRuppFv commented
I believe it is done.
I just need someone to test it (my computer is not making sounds).

2022-09-02 19:52 UTC, 64kramsystem commented
They sound ok to me. I would (personal taste) increase the volume a bit, but it's fine as now.

When I click on "Start Game", I don't hear anything; I don't know if this is intended or not (also on Quit, but that's more likely to be intended).

2022-09-02 19:52 UTC, 64kramsystem reviewed
Tested; notes reported in the PR discussion.

2022-09-02 19:56 UTC, DRuppFv commented
> They sound ok to me. I would (personal taste) increase the volume a bit, but it's fine as now.
> 
> When I click on "Start Game", I don't hear anything; I don't know if this is intended or not (also on Quit, but that's more likely to be intended).

The quit thing can be easily fixed. Just don't close the game immediately. About the start button, it should just play a 
different sound, and i don't know the reason. For now, i'll try to fix my computer before updating this PR

2022-09-02 20:45 UTC, DRuppFv commented
@64kramsystem 
I fixed my computer. The "start game" plays the sound! It's just a different one, if you don't like it, i can change.
About the quit game button... I don't think would be good just make the program wait for 0.5 seconds before it close, then, the best option would be playing the audio in the own "quit game" button code. What do you think about it?

2022-09-03 11:56 UTC, 64kramsystem commented
> I fixed my computer. The "start game" plays the sound! It's just a different one, if you don't like it, i can change.

Ah! I've noticed it. I'm neutral to whatever is used, however, it's hard to notice.

2022-09-03 15:32 UTC, DRuppFv commented
> > I fixed my computer. The "start game" plays the sound! It's just a different one, if you don't like it, i can change.
> 
> Ah! I've noticed it. I'm neutral to whatever is used, however, it's hard to notice.

It's a "normal" sound of "Start Game" button, you can see something like this in a lot of games like Punchy, but you are right. It would be better if we had an loading screen.

And i just put a new one btw

2022-09-19 03:27 UTC, odecay approved these changes

2022-09-19 03:37 UTC, odecay requested changes
It seems like this is almost ready, could you clean up the println?

2022-09-19 03:37 UTC, odecay commented on src/audio.rs
> +        println!("{:?}", event);
This should be removed

2022-09-19 03:53 UTC, odecay approved these changes

2022-09-19 03:53 UTC, odecay commented
bors merge

2022-09-19 03:59 UTC, merged